server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

spring:
  application:
    name: zipkinservice
  boot:
    admin:
      client:
        url: http://localhost:8084
  main:
    allow-bean-definition-overriding: true

management:
  metrics:
    web:
      server:
        auto-time-requests: false
