server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

spring:
  application:
    name: cloud-admin-service
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
