eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

server:
  port: 8101

spring:
  application:
    name: accountweb
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    suffix: .html
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
feign:
  hystrix:
    enabled: true